version: '2'

services:
   web:
    image: inginx
    ports:
    - "8090:80"
   database:
       image: redis
   jenkins:
      image: jenkins:latest
      container_name: jenkins
      user: jenkins
      ports:
      - "8080:8080"
   tomcat: 
     image: tomcat
     container_name: tomcat-container
     ports:
     -"8009:8080" 
